### ISSUE TITLE
Can I propose the different name instead of ECMC_config? 

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/ECMC_config#2]
I would like to have a simple name instead of ECMC_config. The proposal is ecmccfg. What do you think?

**Comment by tboegi** [comment]
No problem from my side.

**Comment by jeonghanlee** [comment]
Can you change it? I like your idea, we would like to use the production.

**Comment by anderssandstrom** [comment]
@jeonghanlee, could it be that you intended to talk to @kivel instead?

**Comment by kivel** [comment]
At PSI modules traditionally use capital letters. But, I'm not a very traditional person, so we can change the name.
Could you explain why ecmccfg is better that ECMC_config?
Basically you can name it whatever you want, the only adjustment would be in the startup.cmd, line 33&34. Otherwise it'll fail to find the template and subs files.

**Comment by jeonghanlee** [comment]
There is no technical reasons. It is too long and CamelCase and special char. 
we use `ecmc`, so I catch your naming skill `_config` to make it short `ecmccfg` or `ecmcfg`. There is no other reasons.  Yes, it is not much we can change only few places where you use `ECMC_config_DIR` or similar require internal variables. Our environment is the same as PSI in terms of the functionalities. 

If you don't like it, I am fine to use `ECMC_config` also. It doesn't change any thing. For me, I would like to keep sync with PSI while we are working on `ecmc`. :)

**Comment by kivel** [comment]
done.
please update your remote-url
https://github.com/paulscherrerinstitute/ecmccfg

**Comment by jeonghanlee** [comment]
We changed the name to ecmccfg.
